version: '3.1'

networks:
  merochat_network:
    ipam:
      config:
        - subnet: 10.0.0.0/24

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: merochat
      POSTGRES_PASSWORD: merochat
      POSTGRES_HOST_AUTH_METHOD: trust

    # copying the index.sql in /docker-entrypoint-initdb.d will make postgresql
    # run the sql file and populate our db
    volumes:
      - ./src/Server/sql/index.sql:/docker-entrypoint-initdb.d/init.sql

    networks:
      merochat_network:
        ipv4_address: 10.0.0.2

    ports:
      - 5432:5432


  # unfortunately, there is no purescript docker image for 0.15.x (only 0.14.x)
  # so we have to start from a node image and grab the release binary ourselves.
  merochat:
    container_name: merochat
    image: "node:16-bullseye"
    volumes:
      - type: bind
        source: .
        target: /merochat
    environment:
      DATABASE_HOST: "10.0.0.2"

    command: sh -c "chmod +x /merochat/entrypoint.sh && /merochat/entrypoint.sh"

    networks:
      merochat_network:
        ipv4_address: 10.0.0.3

    ports:
      - 8000:8000
      - 1339:1339

  # this is just for handling the db from a web gui
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      merochat_network:
        ipv4_address: 10.0.0.4
