module Server.ThreeK.Data where

import Prelude

import Data.Generic.Rep (class Generic)
import Data.HashMap (HashMap)
import Data.HashMap as HM
import Data.Hashable (class Hashable)
import Data.Hashable as HS
import Data.Show.Generic as DGRS
import Data.Tuple (Tuple(..))

data GrammaticalClass
      = Adjective
      | Noun
      | PluralNoun
      | Verb
      | Adverb
      | Other

instance Hashable GrammaticalClass where
      hash = HS.hash <<< show

derive instance Eq GrammaticalClass

derive instance Generic GrammaticalClass _

instance Show GrammaticalClass where
      show = DGRS.genericShow

grammaticalClasses ∷ HashMap GrammaticalClass (HashMap Int (Array String))
grammaticalClasses =
      HM.fromArray
            [ Tuple Other $ HM.fromArray
                    [ Tuple 12 [ "Nevertheless" ]
                    , Tuple 4 [ "Next", "Late", "Less", "Just", "When", "Thus", "Fast", "Soon", "Then", "Much", "Once", "Down", "More", "Away" ]
                    , Tuple 2 [ "Up", "So" ]
                    , Tuple 7 [ "Somehow", "Forever", "Indoors", "Forward", "Quicker", "However" ]
                    , Tuple 11 [ "Furthermore", "Upside-down" ]
                    , Tuple 3 [ "Now", "Yet", "Far", "All" ]
                    , Tuple 6 [ "Aboard", "Enough", "Abroad", "Always", "Anyhow", "Seldom", "Before", "Upbeat", "Indeed", "Around", "During", "Almost" ]
                    , Tuple 8 [ "Somewhat", "Nowadays", "Evermore", "Meantime", "Tomorrow", "Outdoors", "Outwards", "Hitherto", "Overseas", "Anywhere", "Moreover", "Anyplace" ]
                    , Tuple 10 [ "Everywhere", "Afterwards" ]
                    , Tuple 5 [ "Never", "About", "Extra", "Quite", "Later", "Hence", "Aside", "While", "There", "Where", "Twice", "After" ]
                    , Tuple 9 [ "Sometimes", "Meanwhile", "Somewhere", "Elsewhere" ]
                    ]
            , Tuple Verb $ HM.fromArray
                    [ Tuple 5 [ "Pines", "Cries", "Knots", "Bombs", "Rolls", "Stuns", "Hands", "Marks", "Roars", "Mixes", "Loses", "Grins", "Lifts", "Nests", "Votes", "Bores", "Harms", "Yawns", "Cures", "Plays", "Stirs", "Bumps", "Gives", "Sells", "Jails", "Knits", "Times", "Folds", "Emits", "Drags", "Doles", "Flows", "Stabs", "Suits", "Combs", "Prays", "Lands", "Types", "Skips", "Parks", "Shuts", "Feeds", "Snows", "Rings", "Loves", "Yells", "Urges", "Jumps", "Gazes", "Boils", "Feels", "Heaps", "Dares", "Makes", "Keeps", "Fools", "Frets", "Shops", "Traps", "Kills", "Mines", "Faces", "Heats", "Dusts", "Bears", "Notes", "Lists", "Hails", "Holds", "Plans", "Tells", "Avows", "Hates", "Joins", "Tames", "Stops", "Gnaws", "Sways", "Gasps", "Pries", "Leans", "Bites", "Dotes", "Rises", "Fades", "Falls", "Hunts", "Bares", "Heals", "Boxes", "Chips", "Trips", "Sings", "Flies", "Rains", "Picks", "Means", "Hopes", "Fixes", "Steps", "Soaks", "Irons", "Sends", "Earns", "Fumes", "Spots", "Jokes", "Lasts", "Thaws", "Jests", "Barks", "Signs", "Hangs", "Rates", "Hints", "Tours", "Glues", "Rants", "Calls", "Rocks", "Omits", "Dumps", "Lives", "Bakes", "Pulls", "Deals", "Buries", "Trims", "Fires", "Moves", "Cooks", "Pours", "Loans", "Risks", "Dives", "Names", "Dials", "Reads", "Draws", "Chops", "Hears", "Tests", "Faxes", "Fries", "Shows", "Opens", "Beats", "Files", "Peers", "Zooms", "Costs", "Brags", "Jolts", "Parts", "Dupes", "Spins", "Leads", "Knows", "Burns", "Books", "Flaps", "Obeys", "Drops", "Likes", "Curls", "Ticks", "Pelts", "Molts", "Meets", "Swims", "Lends", "Stays", "Slips", "Posts", "Tires", "Cares", "Raves", "Sighs", "Finds", "Bawls", "Docks", "Chews", "Saves", "Locks", "Sails", "Kicks", "Rules", "Seals", "Races", "Takes", "Moors", "Balks", "Bolts", "Turns", "Beams", "Backs", "Hides", "Fears", "Coils", "Talks", "Pokes", "Camps", "Looks", "Yelps", "Trots", "Mails", "Films", "Stars", "Mends", "Melts", "Forms", "Denys", "Gilds", "Clips", "Needs", "Fails", "Quits", "Flees", "Ruins", "Spans", "Aches", "Howls", "Snaps", "Stows", "Edits", "Jeers", "Helps", "Slows" ]
                    , Tuple 14 [ "Cross-examines" ]
                    , Tuple 7 [ "Alleges", "Admires", "Replies", "Brushes", "Hurries", "Happens", "Flosses", "Returns", "Snoozes", "Laments", "Offends", "Shivers", "Extolls", "Alludes", "Travels", "Invests", "Encodes", "Repairs", "Infuses", "Punches", "Reduces", "Marvels", "Borrows", "Relates", "Tries", "Expands", "Attends", "Hinders", "Retorts", "Belongs", "Barters", "Permits", "Suffers", "Bruises", "Freezes", "Assures", "Falters", "Mumbles", "Decides", "Pesters", "Berates", "Guesses", "Vouches", "Removes", "Babbles", "Dresses", "Regrets", "Listens", "Marches", "Implies", "Stashes", "Extends", "Teaches", "Handles", "Rebuffs", "Reveals", "Arrives", "Deserts", "Pledges", "Informs", "Unlocks", "Infects", "Relaxes", "Mutters", "Presses", "Jabbers", "Bestows", "Signals", "Catches", "Behaves", "Affords", "Reaches", "Concurs", "Notices", "Crashes", "Hammers", "Crushes", "Screams", "Vacuums", "Invents", "Soothes", "Forgets", "Rejects", "Escapes", "Sneezes", "Directs", "Crosses", "Empties", "Doubles", "Changes", "Reminds", "Bubbles", "Manages", "Debates", "Numbers", "Ignores", "Charges", "Asserts", "Obtains", "Gathers", "Recites", "Demands", "Affirms", "Damages", "Employs", "Chooses", "Reports", "Answers", "Divides", "Paddles", "Shrieks", "Records", "Sprouts", "Exhorts", "Scrapes", "Becomes", "Remains", "Invites", "Appears", "Appeals", "Advises", "Juggles", "Matters", "Settles", "Bellows", "Fetches", "Shampoos", "Battles", "Repeats", "Rescues", "Expects", "Carries", "Refuses", "Gardens", "Tickles", "Arrests", "Blesses", "Tumbles", "Coaches", "Injures", "Excuses", "Accepts", "Follows", "Ponders", "Unpacks", "Objects", "Depends", "Hijacks", "Insists", "Recalls", "Fastens", "Cajoles", "Retires", "Intends" ]
                    , Tuple 6 [ "Trains", "Broils", "Buzzes", "Quizes", "Forces", "Relies", "Copies", "Envies", "Chides", "Scolds", "Raises", "Spares", "Hovers", "Echoes", "Orders", "Teases", "Strums", "Visits", "Shades", "Thanks", "Grills", "Itches", "Quilts", "Enters", "Trusts", "Covets", "Fences", "Rushes", "Scares", "Rinses", "Alerts", "Fishes", "Severs", "Doubts", "Shoots", "Pedals", "Shrugs", "Begins", "Drives", "Scoffs", "Admits", "Delays", "Greets", "Breaks", "Twists", "Bastes", "Sneaks", "Utters", "Shouts", "Decays", "Snorts", "Gushes", "Stores", "Spends", "Sprays", "Lights", "Avoids", "Speaks", "Paints", "Senses", "Pushes", "Craves", "Sounds", "Prints", "Brings", "Phones", "Pastes", "Starts", "Cracks", "Builds", "Brakes", "Usurps", "Pleads", "Stamps", "Labels", "Places", "Yields", "Unties", "Shares", "Quotes", "Colors", "Chants", "Scoots", "Treats", "States", "Claims", "Trades", "Deters", "Toasts", "Crawls", "Agrees", "Pauses", "Croaks", "Yodels", "Sneers", "Coughs", "Tempts", "Offers", "Singes", "Brands", "Drones", "Tastes", "Drinks", "Exists", "Stuffs", "Spills", "Swoops", "Plants", "Lowers", "Cleans", "Fights", "Sleeps", "Leaves", "Crowds", "Floats", "Enjoys", "Bleeds", "Favors", "Dances", "Steers", "Tosses", "Occurs", "Misses", "Smiles", "Kneels", "Judges", "Learns", "Levels", "Merges", "Snarls", "Boasts", "Covers", "Mourns", "Growls", "Shifts", "Glides", "Slides", "Struts", "Sparks", "Blinks", "Traces", "Hisses", "Laughs", "Passes", "Blurts", "Frames", "Storms", "Founds", "Upsets", "Counts", "Adopts", "Curves", "Allows", "Dreams", "Stands", "Tracks", "Clears", "Reigns", "Tricks", "Chases", "Stunts", "Blinds", "Slices", "Climbs", "Snores", "Values", "Snoops", "Grates", "Taunts", "Knocks", "Points", "Thinks", "Causes", "Spells", "Smells", "Guides", "Elopes", "Pricks", "Smokes", "Closes", "Checks", "Haunts", "Argues", "Strays", "Unites", "Stares", "Voices", "Chomps", "Rhymes", "Guards", "Cycles", "Spoils", "Savors", "Carves", "Cheers", "Expels", "Annoys", "Shocks", "Amuses", "Skates" ]
                    , Tuple 11 [ "Embarrasses", "Understands", "Sympathizes", "Equivocates", "Exaggerates", "Skateboards", "Appreciates", "Strengthens", "Articulates" ]
                    , Tuple 4 [ "Tips", "Uses", "Bats", "Ends", "Mugs", "Hops", "Sees", "Nods", "Runs", "Gets", "Mars", "Puts", "Tows", "Jogs", "Sips", "Oils", "Nags", "Bows", "Pads", "Adds", "Lies", "Does", "Cuts", "Dyes", "Naps", "Skis", "Asks", "Jams", "Pets", "Sows", "Begs", "Hums", "Bars", "Ices", "Jabs", "Robs", "Sets", "Sews", "Ties", "Bids", "Saws", "Rows", "Bets", "Acts", "Bans", "Mows", "Dies", "Rots", "Goes", "Sins", "Fits", "Drys", "Ails", "Bobs", "Owns", "Owes", "Says", "Digs", "Sobs", "Dams", "Pays", "Buys", "Pats" ]
                    , Tuple 12 [ "Concentrates", "Communicates", "Acknowledges" ]
                    , Tuple 3 [ "Has" ]
                    , Tuple 8 [ "Thunders", "Supplies", "Proceeds", "Sputters", "Bargains", "Requests", "Promises", "Explores", "Stammers", "Exclaims", "Bandages", "Radiates", "Shelters", "Reflects", "Inspects", "Explains", "Releases", "Stresses", "Predicts", "Confides", "Trickles", "Attaches", "Improves", "Receives", "Explodes", "Punishes", "Succeeds", "Sketches", "Delivers", "Searches", "Implores", "Inspires", "Stutters", "Suspects", "Sparkles", "Troubles", "Declares", "Delights", "Barrages", "Comforts", "Lightens", "Protects", "Branches", "Breathes", "Commands", "Supposes", "Believes", "Attracts", "Prevents", "Attempts", "Rejoices", "Licenses", "Consists", "Confirms", "Analyzes", "Auctions", "Performs", "Concerns", "Squashes", "Cautions", "Besieges", "Snatches", "Suspends", "Mentions", "Contains", "Produces", "Switches", "Proposes", "Operates", "Counters", "Supports", "Preaches", "Corrects", "Stitches", "Protests", "Enchants", "Programs", "Comments", "Snickers", "Surmises", "Dislikes", "Deserves", "Ventures", "Realizes", "Concedes", "Educates", "Contends", "Collects", "Prepares", "Divulges", "Consents", "Arranges", "Provides", "Applauds", "Bleaches", "Overruns", "Forgives", "Pretends", "Replaces", "Trembles", "Inflates", "Vanishes", "Connects", "Includes", "Suggests", "Dictates", "Examines", "Lectures", "Deceives", "Divorces", "Presents", "Imagines", "Scatters", "Inquires", "Observes", "Compares", "Scorches", "Measures", "Balances", "Precedes", "Approves", "Polishes", "Trounces", "Reverses", "Develops", "Crochets", "Competes", "Upstages", "Grumbles" ]
                    , Tuple 9 [ "Testifies", "Maintains", "Impresses", "Remembers", "Continues", "Announces", "Proclaims", "Describes", "Evacuates", "Professes", "Irritates", "Screeches", "Scratches", "Complains", "Increases", "Discloses", "Theorizes", "Emigrates", "Harnesses", "Overflows", "Punctures", "Interests", "Instructs", "Questions", "Submerges", "Surprises", "Practices", "Foretells", "Memorizes", "Confesses", "Decorates", "Befriends", "Separates", "Burnishes", "Scribbles", "Surrounds", "Preserves", "Exercises", "Deciphers", "Frightens", "Digresses", "Completes", "Threatens", "Considers", "Terrifies", "Concludes", "Possesses", "Stretches" ]
                    , Tuple 10 [ "Challenges", "Telephones", "Recognizes", "Reprimands", "Recommends", "Immigrates", "Vanquishes", "Identifies", "Reiterates", "Stipulates", "Enunciates", "Highlights", "Admonishes", "Interferes", "Criticizes", "Speculates", "Apologizes", "Multiplies", "Volunteers", "Emphasizes", "Entertains", "Encourages", "Introduces", "Postulates", "Transports", "Translates", "Interjects", "Interrupts", "Guarantees", "Broadcasts", "Calculates", "Evaporates", "Influences" ]
                    ]
            , Tuple Noun $ HM.fromArray
                    [ Tuple 13 [ "Komodo Dragon", "Brew Director", "Water Buffalo", "Spirit Healer", "Chorus Singer", "Postal Worker", "Elephant Seal", "Advertisement", "Cryptographer", "Mathematician" ]
                    , Tuple 17 [ "Radio Broadcaster" ]
                    , Tuple 14 [ "Representative", "Businessperson", "Press Operator", "Security Guard", "Street Sweeper" ]
                    , Tuple 16 [ "Flight Attendant" ]
                    , Tuple 9 [ "Structure", "Alligator", "Cassowary", "Deliverer", "Afternoon", "Passenger", "Appliance", "Conductor", "Assistant", "Agreement", "Goldfinch", "Acoustics", "Englander", "Invention", "Breakfast", "Goosander", "Rainstorm", "Butterfly", "Homemaker", "Astronaut", "Treatment", "Existence", "Secretary", "Albatross", "Carpenter", "Sandpiper", "Operation", "Armadillo", "Red Panda", "Selection", "Expansion", "Apparatus", "Furniture", "Jellyfish", "Cormorant", "Transport", "Substance", "Porcupine", "Direction", "Quicksand", "Aftermath", "Insurance", "Authority", "Scapegoat", "Territory", "Amusement", "Crocodile", "Attention", "Dragonfly", "Partridge", "Go-getter", "Digestion", "Wolverine", "Enchanter", "Lunchroom", "Education", "Discovery", "Vegetable", "Knowledge", "Condition", "Scarecrow", "Committee", "Statement", "Principal", "Ecologist", "Economist", "Executive", "Caregiver", "Chauffeur", "Concierge", "Custodian", "Messenger", "Scientist", "Violinist", "Librarian", "Zookeeper", "Zoologist" ]
                    , Tuple 6 [ "Porter", "Battle", "Flight", "Curlew", "Galley", "Drawer", "Rabbit", "Bubble", "Friend", "Sister", "Cattle", "Weight", "Cheese", "Pencil", "Pigeon", "Sponge", "Dinner", "Attack", "Bottle", "Walrus", "Parrot", "Coyote", "Wealth", "Sneeze", "Potato", "Quartz", "Crayon", "Eggnog", "Locket", "Riddle", "Cobweb", "Qualia", "Basket", "Turkey", "Engine", "Stitch", "Thread", "Memory", "Effect", "Square", "Vessel", "Street", "Recess", "Silver", "Icicle", "Profit", "Mitten", "Income", "Minute", "Marble", "Credit", "Person", "Button", "Nation", "Motion", "Oyster", "Amount", "Camera", "Canvas", "Poison", "Expert", "Quince", "Church", "Sailor", "Zipper", "Banana", "Anchor", "Thrill", "Ferret", "Lawyer", "Magpie", "Weasel", "Finger", "Flower", "Salmon", "Clover", "Cactus", "Harbor", "Gerbil", "Chance", "Falcon", "Pocket", "Summer", "Polish", "Kettle", "Degree", "Reason", "Turtle", "Alpaca", "Doctor", "Temper", "Breath", "Faucet", "System", "Beetle", "Advice", "Ticket", "Locust", "Cleric", "Letter", "Health", "Answer", "Border", "Beaver", "Hornet", "Voyage", "Garden", "School", "Theory", "Parcel", "Muscle", "Cellar", "Guitar", "Orange", "Cherry", "Runner", "Middle", "Baboon", "Throne", "Singer", "Hammer", "Monkey", "Pickle", "Cannon", "Number", "Farmer", "Chough", "Grouse", "Beggar", "Plough", "Flavor", "Animal", "Powder", "Lumber", "Needle", "Branch", "Change", "Wombat", "Jaguar", "Dunlin", "Kitten", "Spider", "Celery", "Wrench", "Parent", "Belief", "Design", "Insect", "Action", "Rhythm", "Copper", "Stream", "Office", "Window", "Detail", "Market", "Zephyr", "Record", "Winter", "Circle", "Regret", "Priest", "Butter", "Badger", "Dugong", "Jackal", "Spring", "Collar", "Quiver", "Bucket", "Writer", "String", "Liquid", "Island", "Reward", "Bridge", "Growth", "Ground", "Editor", "Consul", "Marine", "Archer", "Artist", "Author" ]
                    , Tuple 4 [ "Club", "Swan", "Unit", "Fire", "Yoke", "Trip", "Beef", "Bead", "Cast", "Duck", "Mice", "Iron", "Sand", "Rail", "Crib", "Rock", "Soap", "Side", "Bird", "Hope", "Drug", "Look", "Snow", "Sack", "Talk", "Idea", "Card", "Lamp", "Gaur", "Love", "Goat", "Swim", "Lock", "Drop", "Body", "Comb", "Nest", "Wine", "Gold", "Pony", "Drum", "Pipe", "Meal", "Debt", "Slip", "Lead", "Back", "Mine", "Heat", "Hare", "Pail", "Skin", "Song", "Pest", "Coil", "Stew", "Dirt", "Face", "Sign", "Home", "Chin", "Size", "Yarn", "Wood", "Heir", "Bulb", "Push", "Frog", "Whip", "Fact", "Knee", "Mole", "Wish", "Move", "Root", "Bean", "Dust", "Self", "Base", "Hole", "Moon", "Wind", "Newt", "Glue", "Kudu", "Baby", "Game", "Room", "Bear", "Seed", "Fall", "Mask", "Fear", "Joke", "View", "Tent", "Kite", "Male", "Tray", "Wool", "Fold", "Vase", "Boot", "Play", "Sofa", "Wave", "Hill", "Work", "Head", "Pain", "Team", "Bomb", "List", "Word", "Lion", "Twig", "Fang", "Cook", "Beam", "Edge", "Hall", "Cart", "Knot", "Soup", "Crab", "Mass", "Stem", "Copy", "Mint", "Soda", "Nail", "Sink", "Mink", "Fish", "Name", "Ship", "Lace", "Vest", "Bite", "Hour", "Wash", "Plot", "Wing", "Sock", "Hose", "Zinc", "Wall", "Veil", "Coal", "Town", "Cake", "Stop", "Ibex", "Loaf", "Deer", "Hook", "Wire", "Burn", "Join", "Form", "Seat", "Star", "Rook", "Turn", "Maid", "Wren", "Lake", "Bone", "Step", "Rule", "Mist", "Line", "Desk", "Rest", "Week", "Corn", "Gull", "Rose", "Shoe", "Rice", "Door", "Road", "Cord", "Jail", "Hate", "Feet", "Doll", "Pear", "Dime", "Hero", "Cork", "Salt", "Foot", "Dove", "Book", "Food", "Arch", "Crow", "Boss", "Spot", "Silk", "Tree", "Cent", "Sail", "Land", "Time", "Nose", "Gnat", "Rate", "Jump", "Ring", "Army", "Pull", "Bath", "Fork", "Lark", "Oven", "Ball", "Park", "Tail", "Dock", "Walk", "Help", "Suit", "Need", "Camp", "Rain", "Shop", "Vein", "Loss", "Fuel", "Mark", "Clam", "Part", "Horn", "News", "Bike", "Coat", "Boat", "Boar", "Rake", "Milk", "Toad", "Wolf", "Mind", "Meat", "Worm", "Leaf", "Show", "Able", "Year", "Lift", "Bait", "Tank", "Gate", "Farm", "Roof", "Seal", "Bell", "Neck", "Kick", "Flag", "Page", "Yard", "Hawk", "Fowl", "Test", "Wasp", "Note", "Care", "Band", "Hair", "Sort", "Ibis", "Roll", "Cave", "Chef", "Monk" ]
                    , Tuple 5 [ "Thumb", "Actor", "Print", "Tiger", "Shark", "Diver", "Quiet", "Title", "Glass", "Apple", "Metal", "Taste", "Finch", "Quail", "Smile", "Crate", "Flesh", "Waves", "Slope", "Paper", "Waste", "Crush", "Fifth", "Quill", "Spoon", "Humor", "Music", "Stamp", "Honey", "Peace", "Drink", "Lemur", "Jeans", "Class", "Lunch", "Crime", "Fight", "Trail", "Usher", "Feast", "Scarf", "Smoke", "Kitty", "Otter", "Night", "Sleep", "Linen", "Scene", "Robot", "Chair", "Frame", "Wound", "Magic", "Sloth", "River", "Error", "Color", "Goose", "Crook", "House", "Horse", "Laugh", "Spark", "Geese", "Group", "Crowd", "Cable", "Straw", "Price", "Wheel", "Tramp", "Knife", "Crack", "Teeth", "Grade", "Order", "Water", "Sense", "Crown", "Chess", "Birth", "Shape", "Koala", "Brain", "Party", "Cause", "Front", "Cover", "Scent", "Plane", "Plate", "Range", "Paint", "Death", "Guide", "Floor", "Watch", "Table", "Okapi", "Blade", "Stone", "Whale", "Power", "Place", "Route", "Steel", "Truck", "Month", "Sleet", "Patch", "Drain", "Hippo", "Train", "Flock", "Juror", "Brush", "Limit", "Coati", "Eagle", "Board", "Cobra", "Shake", "Heart", "Event", "Skate", "Voice", "Space", "Spade", "Match", "North", "Brass", "Field", "Skunk", "Snail", "Glove", "Juice", "Panda", "Money", "Basin", "Llama", "Light", "Plant", "Thing", "Clock", "Fruit", "Sheet", "Anger", "Slave", "Stage", "Owner", "Moose", "Zebra", "Start", "Cloth", "Nerve", "Beast", "Louse", "Bison", "Noise", "Cloud", "Mouth", "Jelly", "Coast", "Bread", "Coach", "Camel", "Tapir", "Hyena", "Brick", "Dress", "Fixer", "Cough", "Shelf", "Chalk", "Earth", "Eland", "Shade", "Shock", "Trick", "Alley", "Grass", "Store", "Staff", "Shrew", "Skirt", "Heron", "Level", "Flame", "Shirt", "Stove", "Story", "Blood", "Sound", "Force", "Scale", "Robin", "Wrist", "Steam", "Chain", "Mouse", "Point", "Berry", "Raven", "Prose", "Twist", "Ghost", "Quilt", "Snake", "Sugar", "Tooth", "Badge", "Brake", "Judge", "Smell", "Queen", "Verse", "Trade", "Rifle", "Crane", "Sheep", "Grape", "Loris", "Elbow", "Curve", "Grain", "Jewel", "Value", "Alarm", "Paste", "Offer", "Angle", "Touch", "Ocean", "Clerk", "Mason", "Mayor", "Miner", "Model", "Scout", "Smith", "Valet", "Vicar" ]
                    , Tuple 8 [ "Stranger", "Question", "Mandrill", "Boundary", "Learning", "Good-bye", "Kinkajou", "Forester", "Creature", "Calendar", "Dinosaur", "Starling", "Argument", "Business", "Relation", "Industry", "Cemetery", "Birthday", "Friction", "Surprise", "Ancestor", "Mosquito", "Downtown", "Lyrebird", "Sorcerer", "Trousers", "Mountain", "Airplane", "Reporter", "Vacation", "Achiever", "Activity", "Comedian", "Governor", "Increase", "Notebook", "Squirrel", "Children", "Newcomer", "Building", "Seahorse", "Behavior", "Religion", "Approval", "Carriage", "Teaching", "Tendency", "Umbrella", "Sculptor", "Hedgehog", "Decision", "Graduate", "Aardvark", "Beginner", "Anteater", "Porpoise", "Addition", "Pleasure", "Enlistee", "Cherries", "Division", "Position", "Ornament", "Mongoose", "Flamingo", "Antelope", "Stocking", "Kangaroo", "Seashore", "Reaction", "Goldfish", "Minister", "Sidewalk", "Scissors", "Exchange", "Distance", "Sea Lion", "Pheasant", "Dotterel", "Reindeer", "Red Deer", "Property", "Hospital", "Interest", "Baseball", "Language", "Elephant", "Educator", "Engineer", "Explorer", "Exporter", "Chaplain", "Composer", "Magician", "Marketer", "Mechanic", "Muralist", "Musician", "Surveyor", "Animator", "Attorney" ]
                    , Tuple 10 [ "Toothbrush", "Doorkeeper", "Comparison", "Toothpaste", "Salamander", "Polar Bear", "Plantation", "Volleyball", "Playground", "Experience", "Fellowship", "Chinchilla", "Arithmetic", "Suggestion", "Earthquake", "Basketball", "Calculator", "Sea Urchin", "Punishment", "Attraction", "Connection", "Discussion", "Instrument", "Adjustment", "Guinea Pig", "Compatriot", "Chimpanzee", "Government", "Wilderness", "Cab Driver", "Cartoonist", "Contractor", "Ambassador", "Astronomer", "Auctioneer", "Undertaker" ]
                    , Tuple 11 [ "Observation", "Housekeeper", "Floorwalker", "Development", "Guinea Fowl", "Caterpillar", "Nightingale", "Firefighter", "Prairie Dog", "Hummingbird", "Stegosaurus", "Competition", "Flesh Eater", "Grasshopper", "Destruction", "Sand Dollar", "Giant Panda", "Electrician", "Entertainer", "Salesperson", "Saxophonist", "Scuba Diver", "Stockbroker", "Xylophonist" ]
                    , Tuple 12 [ "Choir Member", "Distribution", "Faith Healer", "Spokesperson", "Superstition", "Afterthought", "Sharpshooter", "Organization", "Entomologist", "Entrepreneur", "Exterminator", "Calligrapher", "Cardiologist", "Cartographer", "Mail Carrier", "Manufacturer", "Statistician", "Veterinarian" ]
                    , Tuple 3 [ "Box", "God", "Wax", "Yak", "Tax", "Cub", "Pen", "Ice", "Net", "Can", "Art", "Ray", "Cod", "Zoo", "Ant", "Gnu", "Cap", "Pig", "Rat", "Van", "Jar", "Emu", "Arm", "Fan", "Key", "Dog", "Spy", "Gun", "Lip", "Ape", "Bed", "Ram", "Pot", "Ear", "Cup", "Leg", "War", "Run", "Air", "Egg", "Map", "Ink", "Day", "Pet", "Sky", "Eel", "Eye", "Use", "Toy", "Act", "Tub", "Sea", "Hat", "Tin", "Fog", "Jam", "Low", "Elk", "Bat", "Owl", "Jay", "Car", "Pan", "Cry", "Hen", "Sun", "Pie", "Way", "Cat", "Pin", "Yam", "Toe", "Bun", "Bee", "Oil", "Bit", "End", "Fly", "Fox", "One" ]
                    , Tuple 7 [ "Termite", "Buffalo", "Thought", "Produce", "Popcorn", "Dogfish", "Manatee", "Dolphin", "Chicken", "Process", "Vicuña", "Request", "Panther", "Opinion", "Feeling", "Lookout", "Control", "Payment", "Insurer", "Opossum", "Partner", "Contact", "Library", "Raccoon", "Pelican", "Sweater", "Cabbage", "Aviator", "Lapwing", "Oatmeal", "Narwhal", "Reading", "Mailbox", "Ostrich", "Officer", "Hydrant", "Disease", "Example", "History", "Hamster", "Airport", "Student", "Quarter", "Visitor", "Purpose", "Stretch", "Guanaco", "Haircut", "Creator", "Driving", "Gorilla", "Whistle", "Attempt", "Goshawk", "Lettuce", "Manager", "Curtain", "Caribou", "Cleaner", "Picture", "Railway", "Gazelle", "Harmony", "Octopus", "Fiction", "Tarsier", "Holiday", "Account", "Achieve", "Echidna", "Volcano", "Mammoth", "Current", "Sardine", "Thunder", "Pancake", "Brother", "Country", "Respect", "Impulse", "Morning", "Peafowl", "Giraffe", "Leopard", "Caption", "Trouble", "Balance", "Lobster", "Wallaby", "Apparel", "Stomach", "Balloon", "Comfort", "Cushion", "Company", "Penguin", "Hearing", "Meeting", "Bedroom", "Flagger", "Fighter", "Feather", "Artisan", "Station", "Science", "Hobbies", "Measure", "Channel", "Receipt", "Protest", "Writing", "Support", "Soldier", "Cheetah", "Texture", "Herring", "Journey", "Cowhand", "Laborer", "Machine", "Society", "Mallard", "Believe", "Scholar", "Weather", "Leather", "Plastic", "Insider", "Ladybug", "Quetzal", "Empress", "Emperor", "Captain", "Cashier", "Catcher", "Caterer", "Cellist", "Chemist", "Cobbler", "Courier", "Samurai", "Senator", "Surgeon", "Swimmer", "Veteran", "Athlete" ]
                    ]
            , Tuple Adjective $ HM.fromArray
                    [ Tuple 8 [ "Grateful", "Strident", "Vigilant", "Thorough", "Splendid", "Grounded", "Attached", "Academic", "Adorable", "Metallic", "Granular", "Trusting", "Exciting", "Possible", "Ordinary", "Nautical", "Gruesome", "Thankful", "Creative", "Absolute", "Shocking", "Well-lit", "Colossal", "Jubilant", "Innocent", "Gracious", "Idolized", "Charming", "Confused", "Alarming", "Artistic", "Composed", "Anchored", "Unsteady", "Lustrous", "Majestic", "Decisive", "Precious", "Suburban", "Informal", "Distinct", "Familiar", "Advanced", "Scratchy", "Haunting", "Cheerful", "Critical", "Gleaming", "Agitated", "Careless", "Squiggly", "Impolite", "Cultured", "Fabulous", "Indolent", "Finished", "Writhing", "Striking", "Fearless", "Trifling", "Harmless", "Punctual", "Terrible", "Clueless", "Euphoric", "Favorite", "Fatherly", "Educated", "Positive", "Obedient", "Ironclad", "Friendly", "Gigantic", "Vigorous", "Vengeful", "Reckless", "Carefree", "Truthful", "Terrific", "Negative", "Horrible", "Quixotic", "Tempting", "Infamous", "Well-off", "Discrete", "Bustling", "Tattered", "Definite", "Wretched", "Straight", "Motherly", "Blushing", "Circular", "Detailed", "Pleasant", "Pristine", "Gripping", "Studious", "Intrepid", "Lopsided", "Physical", "Whopping", "Reliable", "Precious", "Internal", "Infinite", "Growling", "Pleasing", "Uncommon", "Spotless", "Constant", "Variable", "Standard", "Ecstatic", "Sardonic", "Flawless", "Fruitful", "Deserted", "Untimely", "Sociable", "Puzzling", "Snarling", "Dazzling", "Forsaken", "Helpless", "Generous", "Unwieldy", "Concrete", "Valuable", "Animated", "Original", "Utilized", "Blissful", "Mindless", "Grizzled", "Outlying", "Polished", "Cautious", "Required", "Handmade", "Aromatic", "Watchful", "Gullible", "Unfolded", "Glorious", "Rotating", "Specific", "Esteemed", "Stunning", "Relieved", "Wrathful", "Peaceful", "Faithful", "Menacing", "Spiteful", "Accurate", "Crushing", "Troubled", "Complete", "Perfumed", "Personal", "Graceful", "Powerful", "Colorful", "Criminal", "Separate", "Periodic", "Heavenly", "Disloyal", "Slippery", "Skeletal", "Electric", "Probable", "Parallel", "Luminous", "Spirited", "Previous", "Frequent", "Sizzling", "Outgoing", "Superior", "Dramatic", "Scornful", "Flippant", "Adorable", "Unlawful", "Tangible", "Diligent", "Fragrant", "Youthful", "Juvenile", "Forceful", "Ultimate", "Fumbling", "Athletic", "Official", "Gorgeous", "Insecure", "Virtuous" ]
                    , Tuple 9 [ "Scholarly", "Delicious", "Indelible", "Misguided", "Excellent", "Unwilling", "Far-flung", "Glamorous", "Wonderful", "Insidious", "Unhealthy", "Impartial", "Wide-eyed", "Pointless", "Concerned", "Venerated", "Identical", "Necessary", "Brilliant", "Unnatural", "Yellowish", "Practical", "Satisfied", "Mortified", "Unsightly", "Insistent", "Qualified", "Evergreen", "Long-term", "Lumbering", "Memorable", "Imperfect", "Worrisome", "Distorted", "Political", "Well-made", "Agreeable", "Difficult", "Unequaled", "Competent", "Agonizing", "Important", "Realistic", "Monstrous", "Traumatic", "Sparkling", "Disguised", "Rewarding", "Neglected", "Flustered", "Luxurious", "Miserable", "Whispered", "Unwelcome", "Overjoyed", "Fortunate", "Marvelous", "Talkative", "Foolhardy", "Repentant", "Downright", "Surprised", "Querulous", "Firsthand", "Breakable", "Bewitched", "Imaginary", "Fantastic", "Essential", "Excitable", "Shameless", "Turbulent", "Acrobatic", "Exhausted", "Deafening", "Dishonest", "Unwritten", "Favorable", "Vivacious", "Dependent", "Ambitious", "Energetic", "Admirable", "Cavernous", "Heartfelt", "Offensive", "Unwitting", "Delirious", "Defensive", "Emotional", "Expensive", "Quizzical", "Miniature", "Clear-cut", "Enchanted", "Nocturnal", "Abandoned", "Ill-fated", "Demanding", "Spherical", "Deficient", "Acclaimed", "Palatable", "Judicious", "Beautiful", "Powerless", "Elaborate", "Sarcastic", "Grandiose", "Well-worn", "Downright", "Infantile", "Conscious", "Sorrowful", "Different", "Authentic", "Whirlwind", "Honorable", "Cluttered", "Pertinent", "Quarterly", "Grotesque", "Revolving", "Immediate", "Frivolous", "Repulsive", "Automatic", "Treasured", "Alienated", "Courteous", "Unselfish", "Hilarious", "Anguished", "Plaintive", "Whimsical", "Exemplary", "Worthless", "Secondary", "Colorless", "Bountiful", "Attentive", "Dangerous" ]
                    , Tuple 5 [ "Minor", "Musty", "Happy", "Round", "Rowdy", "Muddy", "Ideal", "Blank", "White", "Fancy", "Smart", "Noisy", "Wrong", "Unfit", "Quick", "Major", "Joint", "Blind", "Rural", "Regal", "Dense", "Corny", "Early", "Frail", "Brisk", "Every", "Nifty", "Fixed", "Clear", "Weird", "Sandy", "Heavy", "Lumpy", "Flaky", "Sharp", "Scaly", "Scary", "Harsh", "Noted", "Salty", "Light", "Plush", "Meaty", "Sweet", "Black", "Chief", "Grave", "Wordy", "Jumpy", "Super", "Muted", "Sunny", "Curly", "Ample", "Soupy", "Adept", "Fussy", "Tense", "Young", "Equal", "Blond", "Stale", "Close", "These", "Loyal", "Naive", "Pushy", "Soggy", "Agile", "Husky", "Proud", "Jolly", "Front", "Novel", "Pesky", "Mushy", "Third", "Tepid", "Legal", "Bumpy", "Vague", "Fuzzy", "Tubby", "Funny", "Short", "Milky", "Other", "Bogus", "Prime", "Stark", "Upset", "Quiet", "Grown", "Witty", "Mealy", "Valid", "Brief", "Brown", "Steep", "Those", "Which", "Misty", "Brave", "Bulky", "Total", "Whole", "Merry", "Hefty", "Rusty", "Kooky", "Baggy", "Known", "Fluid", "Vivid", "Tired", "Clean", "Hasty", "Small", "Fresh", "Lucky", "Green", "Plain", "Urban", "Staid", "Prize", "Runny", "Vapid", "Royal", "Murky", "Silly", "Bland", "Leafy", "Alive", "Frank", "Right", "Rough", "Weary", "Tough", "Cruel", "Messy", "Spicy", "Livid", "Great", "Eager", "Bowed", "Lanky", "Weepy", "Loose", "Grimy", "Shiny", "Itchy", "False", "Ready", "Hairy", "Ruddy", "Angry", "Jaded", "Jumbo", "Empty", "Crisp", "Fatal", "Bossy", "Moral", "First", "Giddy", "Woozy", "Rapid", "Moist", "Faint", "Dizzy", "Steel", "Glass", "Aware", "Minty", "Dopey", "Gross", "Yummy", "Zesty", "Grand", "Lined", "Gummy", "Tight", "Vital", "Solid", "Silky", "Basic", "Bleak", "Burly", "Swift", "Tasty", "Handy", "Alert", "Testy", "Windy", "Dirty", "Utter", "Giant", "Showy", "Mixed", "Shady" ]
                    , Tuple 6 [ "Closed", "Somber", "Hoarse", "Flimsy", "Annual", "Giving", "Medium", "Humble", "Feisty", "Poised", "Zigzag", "Intent", "Ringed", "Amused", "Common", "Feline", "Coarse", "Expert", "Clumsy", "Square", "Bitter", "Lively", "Creepy", "Warped", "Pretty", "Subtle", "Sweaty", "Nimble", "Fickle", "Strict", "Shoddy", "Pastel", "Unripe", "Dreary", "Untidy", "Stormy", "Barren", "Famous", "Stable", "Homely", "Severe", "Frosty", "Putrid", "Untrue", "Hearty", "Sneaky", "Shabby", "Frugal", "Oblong", "Greedy", "Edible", "Direct", "Hidden", "Acidic", "Silver", "Sugary", "Sudden", "Usable", "Mellow", "Cloudy", "Wilted", "Silent", "Female", "Lonely", "Actual", "Tragic", "Bronze", "Unruly", "Entire", "Fluffy", "Loving", "Grumpy", "Liquid", "Oblong", "Modest", "Paltry", "Droopy", "Slushy", "Creamy", "Secret", "Decent", "Wobbly", "Quirky", "Measly", "Thorny", "Hollow", "Lavish", "Klutzy", "Queasy", "Inborn", "Stingy", "Guilty", "Bouncy", "Upbeat", "Strong", "Unsung", "Knobby", "Normal", "Linear", "Gentle", "Hungry", "Sleepy", "Yellow", "Smooth", "Gloomy", "Boring", "Frayed", "Pricey", "Polite", "French", "Formal", "Robust", "Watery", "Uneven", "Joyful", "Second", "Little", "Trusty", "Useful", "Flawed", "Frizzy", "Wiggly", "Ragged", "Joyous", "Kindly", "Jaunty", "Dental", "Superb", "Yearly", "Costly", "Winged", "Drafty", "Tender", "Gifted", "Cheery", "Forked", "Dapper", "Dreary", "Timely", "Wooden", "Frozen", "Mature", "Crafty", "Single", "Stupid", "Golden", "Lawful", "Flashy", "Glossy", "Aching", "Doting", "Frilly", "Snappy", "Wicked", "Kosher", "Speedy", "Dismal", "Elated", "Exotic", "Modern", "Portly", "Starry", "Unique", "United", "Bright", "Impish", "Jagged", "Honest", "Remote", "Quaint", "Knotty", "Narrow", "Smoggy", "Sparse", "Impure", "Tricky", "Chilly", "Active", "Skinny", "Proper", "Afraid", "Rotten", "Worthy", "Cooked", "Scarce", "Violet", "Scared", "Filthy", "Purple", "Arctic", "Likely", "Clever", "Shrill", "Canine", "Weekly", "Orange", "Better", "Lovely", "Webbed", "Spiffy", "Woeful", "Double", "Candid", "Dismal", "Adored", "Unused", "Jovial", "Ornery", "Cuddly", "Svelte", "Caring", "Frigid", "Broken", "Junior", "Sturdy", "Ornate", "Serene", "Tinted", "Deadly", "Bubbly", "Recent", "Grubby", "Slight", "Meager", "Snoopy", "Vacant", "Simple", "Daring" ]
                    , Tuple 4 [ "Left", "Lost", "Torn", "Damp", "Keen", "Fake", "Soft", "Blue", "Rare", "Wide", "Puny", "Tart", "Loud", "Cool", "Numb", "Vain", "Nice", "Near", "Good", "Calm", "Rash", "Fast", "Next", "Posh", "Used", "Poor", "Bold", "Lone", "Smug", "Tidy", "Cold", "Wild", "Kind", "Each", "Neat", "Wavy", "Sane", "Live", "Past", "Sore", "Evil", "Fond", "Ripe", "Pure", "Bony", "Worn", "Drab", "Fine", "Wary", "Taut", "Tiny", "That", "Glum", "Oval", "Lean", "Flat", "Some", "Cute", "Rich", "Late", "Spry", "Slow", "Open", "Only", "Wise", "Pink", "Able", "Back", "Zany", "Dear", "Full", "Thin", "Oily", "Pale", "Sick", "Real", "Hard", "Dual", "Deep", "This", "Sour", "Safe", "Even", "Aged", "Best", "Vast", "Both", "Trim", "Easy", "Last", "Dark", "High", "Warm", "Mild", "Tall", "Slim", "Twin", "Free", "Busy", "True", "Lazy", "Arid", "Same", "Dull", "Half", "Wiry", "Grim", "Meek", "Gray", "Fair", "Dead", "Idle", "Rosy", "Tame", "Mean" ]
                    , Tuple 11 [ "Sure-footed", "Enlightened", "Cylindrical", "Magnificent", "Prestigious", "Comfortable", "Embarrassed", "Extroverted", "Defenseless", "Embellished", "Illustrious", "Impractical", "Aggravating", "Extra-small", "Kindhearted", "Considerate", "Understated", "Pessimistic", "Frightening", "Big-hearted", "Trustworthy", "Responsible", "Experienced", "Mountainous", "Unimportant", "Cooperative", "Sympathetic", "Warmhearted", "Coordinated", "Outstanding", "Unfortunate", "Neighboring", "Complicated", "Imaginative", "Adventurous", "Intelligent", "Substantial", "Astonishing", "Interesting", "Quarrelsome", "Spectacular", "Appropriate", "Superficial", "Impassioned", "Sentimental", "Waterlogged", "Unconscious", "Descriptive", "Rectangular", "Intentional", "Instructive", "Calculating", "Everlasting", "Unrealistic", "Second-hand" ]
                    , Tuple 12 [ "Multicolored", "Incomparable", "Good-natured", "Questionable", "Self-assured", "Apprehensive", "Accomplished", "Ill-informed", "Self-reliant", "Conventional", "Incompatible", "Lighthearted", "Unacceptable", "Quick-witted", "Affectionate", "Hard-to-find" ]
                    , Tuple 13 [ "Sophisticated", "Insubstantial", "Kaleidoscopic", "Inexperienced", "Knowledgeable", "Irresponsible", "Compassionate", "International", "Imperturbable", "Old-fashioned", "Biodegradable", "Well-informed" ]
                    , Tuple 14 [ "Quintessential", "Happy-go-lucky", "Impressionable" ]
                    , Tuple 3 [ "All", "Red", "Tan", "Dim", "Wee", "New", "Key", "Few", "Shy", "Far", "Bad", "Wry", "Icy", "Apt", "Our", "Dry", "Mad", "Sad", "Any", "Low", "Wet", "Hot", "Wan", "Odd", "Old" ]
                    , Tuple 7 [ "Unknown", "Eminent", "Welcome", "Foolish", "Optimal", "Limited", "Likable", "Scrawny", "Spotted", "Angelic", "Crooked", "Yawning", "Pungent", "Jealous", "Damaged", "Decimal", "Mundane", "Puzzled", "Pointed", "Mammoth", "Devoted", "Admired", "Ashamed", "Subdued", "Enraged", "Amusing", "Austere", "Soulful", "Belated", "Scented", "Envious", "Genuine", "Untried", "Unaware", "Complex", "Natural", "Delayed", "Antique", "Unlined", "Stained", "Buzzing", "Overdue", "Prudent", "Radiant", "Helpful", "Unusual", "Fitting", "Violent", "Unlucky", "Roasted", "Stylish", "Assured", "Lovable", "Regular", "Knowing", "Rubbery", "Babyish", "Immense", "Profuse", "Present", "Potable", "Healthy", "Shallow", "Careful", "Plastic", "Trained", "Growing", "Popular", "Gleeful", "Warlike", "Leading", "Alarmed", "Fearful", "Failing", "Focused", "Wealthy", "Miserly", "Noxious", "Jittery", "Elderly", "Idiotic", "Nervous", "Glaring", "Distant", "Peppery", "Nonstop", "Muffled", "Pleased", "Faraway", "Dearest", "Orderly", "Thrifty", "General", "Amazing", "Visible", "Oddball", "Opulent", "Shadowy", "Private", "Darling", "Vibrant", "Lasting", "Harmful", "Notable", "Medical", "Vicious", "Unhappy", "Content", "Made-up", "Elastic", "Organic", "Exalted", "Dutiful", "Grouchy", "Strange", "Illegal", "Blaring", "Boiling", "Zealous", "Shocked", "Perfect", "Humming", "Dimpled", "Playful", "Honored", "Ancient", "Awesome", "Velvety", "Virtual", "Parched", "Partial", "Teeming", "Far-off", "Buttery", "Awkward", "Classic", "Elegant", "Useless", "Serious", "Average", "Tedious", "Weighty", "Worldly", "Similar", "Obvious", "Offbeat", "Bruised", "Defiant", "Hopeful", "Ethical", "Starchy", "Earnest", "Uniform", "Worried", "Digital", "Crowded", "Trivial", "Capital", "Melodic", "Willing", "Beloved", "Another", "Winding", "Monthly", "Primary", "Distant", "Flowery", "Spanish" ]
                    , Tuple 10 [ "Delectable", "Overcooked", "Frightened", "Unfinished", "Well-to-do", "Definitive", "Reflecting", "Easy-going", "Impressive", "Determined", "Unpleasant", "Tremendous", "Reasonable", "Sweltering", "Glistening", "Remarkable", "Optimistic", "Motionless", "Noteworthy", "Disastrous", "Remorseful", "Altruistic", "Immaterial", "Authorized", "Legitimate", "Respectful", "Profitable", "Impossible", "Bite-sized", "Glittering", "Scientific", "Avaricious", "Supportive", "Worthwhile", "Victorious", "Acceptable", "Thoughtful", "Thunderous", "Improbable", "Extraneous", "Overlooked", "Short-term", "Passionate", "Enchanting", "Elementary", "Jam-packed", "High-level", "Villainous", "Suspicious", "Beneficial", "Negligible", "Nutritious", "Delightful", "Forthright", "Monumental", "Occasional", "Simplistic", "Stupendous", "Harmonious", "Outrageous", "Tremendous", "Courageous", "Threadbare", "Burdensome", "Cultivated", "Cumbersome", "Elliptical", "Triangular", "Dependable", "Mysterious", "Shimmering", "Outlandish", "Infatuated", "Gregarious", "Incomplete", "Idealistic", "Flickering", "Productive", "Immaculate", "Functional", "Incredible", "Impeccable", "Hospitable", "Equatorial", "Verifiable", "Serpentine", "Aggressive", "Gargantuan", "Celebrated" ]
                    , Tuple 15 [ "Well-documented", "Black-and-white", "Inconsequential" ]
                    ]
            , Tuple Adverb $ HM.fromArray
                    [ Tuple 7 [ "Happily", "Sharply", "Sweetly", "Tensely", "Briskly", "Heavily", "Readily", "Loyally", "Angrily", "Lithely", "Vaguely", "Orderly", "Noisily", "Clearly", "Tightly", "Luckily", "Rightly", "Proudly", "Nastily", "Wearily", "Bravely", "Plainly", "Tepidly", "Crossly", "Sternly", "Harshly", "Shrilly", "Monthly", "Lightly", "Shortly", "Nightly", "Merrily", "Fatally", "Thereby", "Chiefly", "Roughly", "Densely", "Finally", "Bleakly", "Hastily", "Visibly", "Closely", "Wrongly", "Greatly", "Blindly", "Acutely", "Usually", "Scarily", "Utterly", "Loosely", "Loftily", "Cleanly", "Already", "Rapidly", "Frankly", "Quietly", "Morally", "Quickly", "Equally", "Swiftly", "Rigidly", "Exactly", "Crazily", "Briefly", "Shakily", "Cruelly", "Totally", "Eagerly" ]
                    , Tuple 8 [ "Hungrily", "Covertly", "Knottily", "Reliably", "Properly", "Normally", "Visually", "Casually", "Silently", "Dreamily", "Possibly", "Politely", "Probably", "Fiercely", "Steadily", "Docilely", "Joyfully", "Cleverly", "Queasily", "Intently", "Directly", "Lovingly", "Famously", "Urgently", "Bitterly", "Securely", "Mortally", "Jauntily", "Markedly", "Slightly", "Clumsily", "Daintily", "Honestly", "Actually", "Cloudily", "Daringly", "Suitably", "Recently", "Upwardly", "Smoothly", "Vacantly", "Speedily", "Sedately", "Scarcely", "Woefully", "Strictly", "Fluently", "Quaintly", "Wickedly", "Terribly", "Formerly", "Solemnly", "Jaggedly", "Entirely", "Sleepily", "Actively", "Jovially", "Prettily", "Joyously", "Worthily", "Formally", "Tenderly", "Suddenly", "Verbally", "Candidly", "Promptly", "Usefully", "Commonly", "Finitely", "Randomly", "Heartily", "Decently", "Brightly", "Unkindly", "Brutally", "Mightily", "Quirkily", "Greedily", "Inwardly", "Shoddily" ]
                    , Tuple 10 [ "Splendidly", "Measurably", "Confusedly", "Handsomely", "Gracefully", "Ultimately", "Diligently", "Positively", "Vigorously", "Selflessly", "Blissfully", "Humorously", "Constantly", "Admiringly", "Poetically", "Eventually", "Officially", "Singularly", "Materially", "Externally", "Habitually", "Abnormally", "Vertically", "Explicitly", "Poignantly", "Diagonally", "Negatively", "Carelessly", "Absolutely", "Informally", "Presumably", "Stealthily", "Generously", "Divisively", "Ruthlessly", "Recklessly", "Hopelessly", "Gratefully", "Ironically", "Innocently", "Repeatedly", "Hauntingly", "Believably", "Reasonably", "Invariably", "Painlessly", "Powerfully", "Frequently", "Especially", "Separately", "Physically", "Obligingly", "Skillfully", "Previously", "Vigilantly", "Abundantly", "Youthfully", "Internally", "Graciously", "Ordinarily", "Charmingly", "Inevitably", "Studiously", "Faithfully", "Doubtfully", "Thankfully", "Colorfully", "Yearningly", "Rightfully", "Menacingly", "Truthfully", "Boastfully", "Remarkably", "Punctually", "Delicately", "Eloquently", "Childishly", "Jubilantly", "Completely", "Sheepishly", "Infinitely", "Puzzlingly", "Cautiously", "Personally", "Disorderly", "Cheerfully", "Grudgingly", "Unbearably" ]
                    , Tuple 11 [ "Haphazardly", "Responsibly", "Resentfully", "Unanimously", "Righteously", "Unfavorably", "Temporarily", "Universally", "Voluntarily", "Luxuriously", "Startlingly", "Principally", "Fashionably", "Wonderfully", "Customarily", "Emotionally", "Ferociously", "Extensively", "Indubitably", "Comfortably", "Respectably", "Brilliantly", "Exclusively", "Exceedingly", "Elaborately", "Immediately", "Incessantly", "Secretively", "Evocatively", "Unselfishly", "Accordingly", "Stressfully", "Beautifully", "Impatiently", "Quizzically", "Unnaturally", "Shamelessly", "Appreciably", "Financially", "Searchingly", "Incorrectly", "Unwillingly", "Spiritually", "Irrefutably", "Unfailingly", "Dangerously", "Potentially", "Essentially", "Differently", "Reluctantly", "Fortunately", "Strenuously", "Vivaciously", "Perpetually", "Efficiently", "Frantically", "Unabashedly", "Unethically", "Continually" ]
                    , Tuple 15 [ "Extraordinarily", "Overconfidently", "Sympathetically", "Compassionately", "Whole-heartedly" ]
                    , Tuple 4 [ "Only", "Very", "Well" ]
                    , Tuple 14 [ "Intermittently", "Optimistically", "Scientifically", "Unquestionably", "Affectionately", "Coincidentally", "Absentmindedly", "Systematically", "Half-heartedly", "Unimpressively" ]
                    , Tuple 13 [ "Knowledgeably", "Spectacularly", "Substantially", "Imaginatively", "Independently", "Affirmatively", "Exceptionally", "Unnecessarily", "Significantly", "Bewilderingly", "Paradoxically", "Inquisitively", "Considerately", "Unemotionally", "Silicitiously", "Kindheartedly", "Unfortunately", "Energetically", "Appropriately", "Reproachfully", "Astonishingly", "Interestingly", "Questioningly", "Intelligently", "Superficially" ]
                    , Tuple 9 [ "Selfishly", "Viciously", "Intensely", "Restfully", "Partially", "Correctly", "Expressly", "Sincerely", "Playfully", "Favorably", "Ethically", "Agreeably", "Currently", "Earnestly", "Elegantly", "Painfully", "Furiously", "Worriedly", "Excitedly", "Eternally", "Generally", "Valiantly", "Magically", "Carefully", "Perfectly", "Cunningly", "Miserably", "Medically", "Endlessly", "Zestfully", "Routinely", "Patiently", "Curiously", "Uselessly", "Instantly", "Enjoyably", "Fervently", "Genuinely", "Specially", "Mockingly", "Immensely", "Dastardly", "Healthily", "Evidently", "Jealously", "Longingly", "Supremely", "Compactly", "Hurriedly", "Outwardly", "Stylishly", "Naturally", "Foolishly", "Seemingly", "Bashfully", "Defiantly", "Irritably", "Gleefully", "Awkwardly", "Extremely", "Assuredly", "Obviously", "Presently", "Willingly", "Girlishly", "Helpfully", "Yesterday", "Nervously", "Seriously", "Hatefully", "Willfully", "Invisibly", "Knavishly", "Amazingly", "Ominously", "Regularly", "Gradually", "Kiddingly", "Coaxingly", "Certainly", "Uniformly", "Zealously", "Anxiously", "Joylessly", "Knowingly" ]
                    , Tuple 16 [ "Enthusiastically" ]
                    , Tuple 12 [ "Methodically", "Hysterically", "Sporadically", "Specifically", "Majestically", "Victoriously", "Deliberately", "Structurally", "Mysteriously", "Unexpectedly", "Impressively", "Sufficiently", "Respectfully", "Reassuringly", "Unskillfully", "Periodically", "Successfully", "Outrageously", "Surprisingly", "Unbelievably", "Particularly", "Persistently", "Effortlessly", "Tremendously", "Immeasurably", "Infrequently", "Accidentally", "Bewilderedly", "Frenetically", "Ridiculously", "Suspiciously", "Meaningfully", "Courageously", "Mechanically", "Consequently", "Persuasively", "Passionately", "Continuously", "Considerably", "Horizontally", "Subsequently", "Thoughtfully", "Questionably", "Begrudgingly", "Judgmentally", "Consistently", "Delightfully", "Harmoniously", "Dramatically", "Unilaterally", "Occasionally", "Identifiably" ]
                    , Tuple 5 [ "Daily", "Fully", "Sadly", "Fiery", "Icily", "Slyly", "Every", "Dimly", "Today", "Oddly", "Still", "Early", "Madly", "Shyly", "Truly" ]
                    , Tuple 3 [ "Why" ]
                    , Tuple 6 [ "Highly", "Solely", "Dearly", "Likely", "Lastly", "Safely", "Wisely", "Justly", "Surely", "Warmly", "Yearly", "Weekly", "Barely", "Primly", "Freely", "Coolly", "Poorly", "Vastly", "Fondly", "Merely", "Lately", "Nearly", "Wildly", "Lazily", "Simply", "Boldly", "Mainly", "Easily", "Mostly", "Busily", "Rarely", "Anyway", "Evenly", "Dopily", "Richly", "Openly", "Deftly", "Grimly", "Keenly", "Subtly", "Meanly", "Loudly", "Weakly", "Lively", "Zanily", "Calmly", "Nosily", "Nicely", "Vainly", "Gently", "Coldly", "Nearby", "Darkly", "Slowly", "Neatly", "Really", "Hourly", "Gladly", "Deeply", "Kindly", "Fairly", "Cutely" ]
                    ]
            , Tuple PluralNoun $ HM.fromArray
                    [ Tuple 11 [ "Comparisons", "Cassowaries", "Toothpastes", "Salamanders", "Polar Bears", "Plantations", "Goldfinches", "Volleyballs", "Playgrounds", "Experiences", "Fellowships", "Butterflies", "Chinchillas", "Arithmetics", "Suggestions", "Earthquakes", "Basketballs", "Calculators", "Sea Urchins", "Punishments", "Secretaries", "Albatrosses", "Attractions", "Connections", "Apparatuses", "Jellyfishes", "Discussions", "Instruments", "Adjustments", "Guinea Pigs", "Authorities", "Territories", "Compatriots", "Chimpanzees", "Governments", "Dragonflies", "Discoveries", "Cab Drivers", "Cartoonists", "Contractors", "Salespeople", "Ambassadors", "Astronomers", "Auctioneers", "Undertakers" ]
                    , Tuple 8 [ "Termites", "Thoughts", "Produces", "Popcorns", "Manatees", "Dolphins", "Chickens", "Vicuñas", "Requests", "Panthers", "Opinions", "Feelings", "Lookouts", "Controls", "Payments", "Potatoes", "Insurers", "Quartzes", "Opossums", "Partners", "Contacts", "Raccoons", "Sweaters", "Cabbages", "Aviators", "Stitches", "Lapwings", "Oatmeals", "Memories", "Narwhals", "Readings", "Recesses", "Hydrants", "Diseases", "Examples", "Hamsters", "Airports", "Students", "Quarters", "Visitors", "Canvases", "Purposes", "Haircuts", "Churches", "Creators", "Drivings", "Gorillas", "Whistles", "Attempts", "Cactuses", "Goshawks", "Lettuces", "Managers", "Curtains", "Caribous", "Polishes", "Cleaners", "Pictures", "Railways", "Gazelles", "Fictions", "Tarsiers", "Holidays", "Accounts", "Achieves", "Echidnas", "Mammoths", "Currents", "Sardines", "Thunders", "Pancakes", "Brothers", "Theories", "Cherries", "Respects", "Impulses", "Mornings", "Peafowls", "Giraffes", "Leopards", "Captions", "Troubles", "Balances", "Shooters", "Lobsters", "Apparels", "Balloons", "Comforts", "Cushions", "Penguins", "Hearings", "Meetings", "Bedrooms", "Branches", "Flaggers", "Fighters", "Feathers", "Artisans", "Stations", "Sciences", "Measures", "Channels", "Receipts", "Protests", "Writings", "Supports", "Soldiers", "Celeries", "Wrenches", "Cheetahs", "Textures", "Herrings", "Journeys", "Cowhands", "Laborers", "Machines", "Mallards", "Believes", "Scholars", "Weathers", "Leathers", "Plastics", "Insiders", "Ladybugs", "Quetzals", "Emperors", "Captains", "Cashiers", "Catchers", "Caterers", "Cellists", "Chemists", "Cobblers", "Coroners", "Couriers", "Samurais", "Senators", "Sweepers", "Surgeons", "Swimmers", "Veterans", "Athletes" ]
                    , Tuple 4 [ "Gods", "Yaks", "Cubs", "Ices", "Nets", "Cans", "Arts", "Rays", "Cods", "Zoos", "Ants", "Gnus", "Caps", "Pigs", "Vans", "Jars", "Hots", "Emus", "Arms", "Fans", "Keys", "Dogs", "Lips", "Apes", "Beds", "Rams", "Pots", "Ears", "Cups", "Legs", "Wars", "Rods", "Runs", "Airs", "Eggs", "Maps", "Inks", "Days", "Pets", "Eels", "Eyes", "Uses", "Acts", "Tubs", "Seas", "Hats", "Tins", "Fogs", "Jams", "Lows", "Elks", "Bats", "Owls", "Jays", "Cars", "Pans", "Hens", "Suns", "Pies", "Ways", "Cats", "Pins", "Yams", "Toes", "Buns", "Bees", "Oils", "Bits", "Ends", "Ones" ]
                    , Tuple 13 [ "Choir Members", "Distributions", "Faith Healers", "Superstitions", "Water Buffalo", "Stegosauruses", "Afterthoughts", "Organizations", "Entomologists", "Entrepreneurs", "Exterminators", "Calligraphers", "Cardiologists", "Cartographers", "Mail Carriers", "Manufacturers", "Statisticians", "Veterinarians" ]
                    , Tuple 15 [ "Representatives", "Press Operators", "Security Guards", "Business people" ]
                    , Tuple 14 [ "Komodo Dragons", "Brew Directors", "Spirit Healers", "Chorus Singers", "Postal Workers", "Elephant Seals", "Advertisements", "Cryptographers", "Mathematicians" ]
                    , Tuple 10 [ "Structures", "Alligators", "Boundaries", "Deliverers", "Afternoons", "Passengers", "Appliances", "Conductors", "Assistants", "Businesses", "Agreements", "Industries", "Cemeteries", "Englanders", "Inventions", "Breakfasts", "Goosanders", "Rainstorms", "Homemakers", "Astronauts", "Treatments", "Existences", "Activities", "Carpenters", "Sandpipers", "Operations", "Armadillos", "Red Pandas", "Selections", "Tendencies", "Expansions", "Cormorants", "Transports", "Substances", "Porcupines", "Directions", "Quicksands", "Aftermaths", "Insurances", "Scapegoats", "Amusements", "Crocodiles", "Attentions", "Partridges", "Go-getters", "Digestions", "Wolverines", "Enchanters", "Lunchrooms", "Goldfishes", "Educations", "Vegetables", "Conditions", "Properties", "Scarecrows", "Committees", "Statements", "Principals", "Ecologists", "Economists", "Executives", "Chauffeurs", "Concierges", "Custodians", "Messengers", "Scientists", "Violinists", "Librarians", "Zookeepers", "Zoologists" ]
                    , Tuple 18 [ "Radio Broadcasters" ]
                    , Tuple 7 [ "Porters", "Battles", "Flights", "Curlews", "Galleys", "Drawers", "Rabbits", "Buffalo", "Bubbles", "Friends", "Sisters", "Weights", "Cheeses", "Glasses", "Pencils", "Pigeons", "Finches", "Sponges", "Dinners", "Attacks", "Fleshes", "Bottles", "Parrots", "Coyotes", "Wealths", "Hobbies", "Sneezes", "Crushes", "Crayons", "Eggnogs", "Lockets", "Riddles", "Classes", "Cobwebs", "Lunches", "Qualias", "Kitties", "Baskets", "Turkeys", "Engines", "Threads", "Effects", "Squares", "Vessels", "Streets", "Silvers", "Icicles", "Profits", "Mittens", "Incomes", "Minutes", "Marbles", "Credits", "Chesses", "Buttons", "Nations", "Motions", "Oysters", "Parties", "Amounts", "Cameras", "Poisons", "Throats", "Experts", "Quinces", "Sailors", "Zippers", "Bananas", "Anchors", "Thrills", "Watches", "Ferrets", "Lawyers", "Magpies", "Weasels", "Shelves", "Fingers", "Flowers", "Salmons", "Clovers", "Harbors", "Gerbils", "Chances", "Falcons", "Pockets", "Patches", "Summers", "Kettles", "Degrees", "Reasons", "Turtles", "Alpacas", "Brushes", "Doctors", "Tempers", "Breaths", "Faucets", "Systems", "Beetles", "Advices", "Tickets", "Matches", "Locusts", "Brasses", "Clerics", "Letters", "Healths", "Answers", "Borders", "Beavers", "Hornets", "Voyages", "Gardens", "Schools", "Parcels", "Muscles", "Cellars", "Guitars", "Oranges", "Runners", "Middles", "Baboons", "Jellies", "Thrones", "Coaches", "Singers", "Prisons", "Hammers", "Monkeys", "Pickles", "Cannons", "Dresses", "Numbers", "Farmers", "Choughs", "Grouses", "Beggars", "Ploughs", "Flavors", "Animals", "Grasses", "Powders", "Lumbers", "Needles", "Changes", "Stories", "Wombats", "Jaguars", "Dunlins", "Kittens", "Spiders", "Parents", "Beliefs", "Designs", "Berries", "Insects", "Actions", "Rhythms", "Coppers", "Streams", "Offices", "Windows", "Details", "Markets", "Zephyrs", "Records", "Winters", "Circles", "Regrets", "Priests", "Butters", "Badgers", "Dugongs", "Lorises", "Jackals", "Springs", "Collars", "Quivers", "Buckets", "Writers", "Strings", "Liquids", "Islands", "Rewards", "Touches", "Bridges", "Growths", "Grounds", "Editors", "Consuls", "Marines", "Streets", "Archers", "Artists", "Authors" ]
                    , Tuple 5 [ "Swans", "Units", "Boxes", "Fires", "Yokes", "Trips", "Beefs", "Casts", "Ducks", "Irons", "Sands", "Taxes", "Cribs", "Rocks", "Soaps", "Sides", "Birds", "Hopes", "Looks", "Snows", "Sacks", "Talks", "Ideas", "Cards", "Lamps", "Gaurs", "Goats", "Waves", "Swims", "Locks", "Drops", "Combs", "Nests", "Wines", "Golds", "Drums", "Pipes", "Meals", "Debts", "Slips", "Leads", "Backs", "Mines", "Heats", "Hares", "Pails", "Skins", "Songs", "Pests", "Coils", "Stews", "Dirts", "Faces", "Signs", "Homes", "Chins", "Sizes", "Yarns", "Woods", "Heirs", "Bulbs", "Frogs", "Whips", "Facts", "Knees", "Moles", "Moves", "Roots", "Beans", "Dusts", "Selfs", "Bases", "Holes", "Moons", "Winds", "Newts", "Glues", "Kudus", "Games", "Rooms", "Bears", "Falls", "Masks", "Fears", "Jokes", "Views", "Tents", "Kites", "Males", "Trays", "Wools", "Folds", "Vases", "Boots", "Plays", "Spies", "Sofas", "Waves", "Hills", "Works", "Heads", "Pains", "Teams", "Bombs", "Lists", "Words", "Lions", "Twigs", "Fangs", "Cooks", "Halls", "Carts", "Knots", "Soups", "Crabs", "Stems", "Mints", "Sodas", "Sinks", "Minks", "Names", "Ships", "Laces", "Vests", "Bites", "Hours", "Plots", "Wings", "Socks", "Hoses", "Zincs", "Walls", "Veils", "Coals", "Towns", "Stops", "Loafs", "Deers", "Skies", "Wires", "Burns", "Joins", "Forms", "Seats", "Stars", "Rooks", "Turns", "Maids", "Wrens", "Lakes", "Steps", "Rules", "Mists", "Lines", "Desks", "Rests", "Weeks", "Corns", "Gulls", "Roses", "Shoes", "Rices", "Doors", "Roads", "Cords", "Jails", "Hates", "Dolls", "Pears", "Dimes", "Corks", "Salts", "Foots", "Doves", "Books", "Foods", "Crows", "Spots", "Silks", "Trees", "Cents", "Sails", "Lands", "Times", "Noses", "Gnats", "Rates", "Jumps", "Rings", "Baths", "Forks", "Larks", "Ovens", "Balls", "Parks", "Cries", "Tails", "Docks", "Walks", "Helps", "Suits", "Needs", "Camps", "Rains", "Shops", "Veins", "Fuels", "Marks", "Clams", "Parts", "Horns", "Bikes", "Coats", "Boats", "Boars", "Rakes", "Toads", "Wolfs", "Minds", "Meats", "Worms", "Leafs", "Shows", "Ables", "Years", "Lifts", "Baits", "Tanks", "Gates", "Farms", "Roofs", "Seals", "Bells", "Necks", "Kicks", "Flags", "Pages", "Yards", "Hawks", "Fowls", "Tests", "Wasps", "Flies", "Notes", "Cares", "Bands", "Hairs", "Sorts", "Rolls", "Foxes", "Caves", "Chefs", "Monks" ]
                    , Tuple 6 [ "Thumbs", "Actors", "Prints", "Tigers", "Sharks", "Divers", "Quiets", "Titles", "Apples", "Metals", "Tastes", "Quails", "Smiles", "Crates", "Slopes", "Papers", "Wastes", "Fifths", "Quills", "Spoons", "Humors", "Musics", "Stamps", "Honeys", "Bodies", "Peaces", "Drinks", "Ponies", "Lemurs", "Crimes", "Fights", "Trails", "Ushers", "Feasts", "Scarfs", "Smokes", "Otters", "Nights", "Sleeps", "Linens", "Scenes", "Robots", "Chairs", "Frames", "Magics", "Sloths", "Rivers", "Errors", "Colors", "Gooses", "Crooks", "Houses", "Horses", "Pushes", "Laughs", "Sparks", "Wishes", "Screws", "Groups", "Crowds", "Cables", "Straws", "Prices", "Wheels", "Tramps", "Knifes", "Babies", "Cracks", "Grades", "Orders", "Bushes", "Waters", "Senses", "Crowns", "People", "Births", "Shapes", "Koalas", "Brains", "Causes", "Fronts", "Covers", "Scents", "Planes", "Plates", "Ranges", "Paints", "Deaths", "Guides", "Floors", "Tables", "Okapis", "Blades", "Stones", "Whales", "Powers", "Places", "Routes", "Steels", "Trucks", "Months", "Sleets", "Drains", "Hippos", "Trains", "Flocks", "Jurors", "Limits", "Coatis", "Eagles", "Boards", "Cobras", "Shakes", "Masses", "Hearts", "Events", "Copies", "Skates", "Voices", "Fishes", "Spaces", "Spades", "Norths", "Fields", "Skunks", "Snails", "Gloves", "Pandas", "Washes", "Moneys", "Basins", "Llamas", "Lights", "Plants", "Things", "Clocks", "Ibexes", "Sheets", "Angers", "Slaves", "Stages", "Owners", "Zebras", "Starts", "Cloths", "Nerves", "Beasts", "Louses", "Bisons", "Noises", "Clouds", "Mouths", "Coasts", "Breads", "Camels", "Heroes", "Tapirs", "Hyenas", "Bricks", "Fixers", "Shames", "Coughs", "Chalks", "Earths", "Bosses", "Elands", "Shades", "Shocks", "Tricks", "Alleys", "Stores", "Staffs", "Shrews", "Herons", "Levels", "Flames", "Armies", "Shirts", "Stoves", "Bloods", "Sounds", "Forces", "Scales", "Robins", "Wrists", "Steams", "Chains", "Mouses", "Points", "Ravens", "Proses", "Losses", "Twists", "Ghosts", "Newses", "Quilts", "Snakes", "Sugars", "Tooths", "Badges", "Brakes", "Judges", "Smells", "Queens", "Verses", "Trades", "Rifles", "Cranes", "Grapes", "Elbows", "Curves", "Grains", "Jewels", "Values", "Alarms", "Pastes", "Ibises", "Offers", "Oceans", "Clerks", "Masons", "Mayors", "Miners", "Models", "Scouts", "Smiths", "Valets", "Vicars" ]
                    , Tuple 12 [ "Toothbrushes", "Observations", "Housekeepers", "Floorwalkers", "Developments", "Spokespeople", "Guinea Fowls", "Caterpillars", "Firefighters", "Prairie Dogs", "Hummingbirds", "Competitions", "Flesh Eaters", "Grasshoppers", "Destructions", "Wildernesses", "Sand Dollars", "Giant Pandas", "Electricians", "Entertainers", "Saxophonists", "Scuba Divers", "Stockbrokers", "Xylophonists" ]
                    , Tuple 17 [ "Flight Attendants" ]
                    , Tuple 9 [ "Strangers", "Questions", "Dogfishes", "Mandrills", "Processes", "Learnings", "Good-byes", "Kinkajous", "Foresters", "Creatures", "Calendars", "Dinosaurs", "Starlings", "Arguments", "Libraries", "Relations", "Birthdays", "Frictions", "Commoners", "Surprises", "Ancestors", "Downtowns", "Mailboxes", "Ostriches", "Lyrebirds", "Sorcerers", "Histories", "Mountains", "Airplanes", "Reporters", "Vacations", "Achievers", "Stretches", "Comedians", "Governors", "Increases", "Notebooks", "Squirrels", "Newcomers", "Buildings", "Seahorses", "Behaviors", "Religions", "Harmonies", "Approvals", "Octopuses", "Carriages", "Teachings", "Umbrellas", "Sculptors", "Hedgehogs", "Decisions", "Graduates", "Aardvarks", "Volcanoes", "Beginners", "Acoustics", "Anteaters", "Porpoises", "Additions", "Enlistees", "Countries", "Divisions", "Ornaments", "Mongooses", "Flamingos", "Wallabies", "Stomaches", "Companies", "Antelopes", "Stockings", "Kangaroos", "Seashores", "Reactions", "Ministers", "Sidewalks", "Exchanges", "Distances", "Sea Lions", "Pheasants", "Dotterels", "Societies", "Reindeers", "Red Deers", "Hospitals", "Interests", "Baseballs", "Languages", "Elephants", "Educators", "Empresses", "Engineers", "Explorers", "Exporters", "Chaplains", "Composers", "Magicians", "Marketers", "Mechanics", "Muralists", "Musicians", "Surveyors", "Animators", "Attorneys" ]
                    ]
            ]
